---
title: "10_3Q8"
author: "David Beauchemin"
date: "6 décembre 2017"
output: pdf_document
---

# 10_3Q8

## A)
```{r}
distributionFunction <- function(x1, x2){
     1 - (exp(-2 * x1) + exp(-2 * x2) - exp(-2 * (x1 + x2)))^(0.5)
}
sapply(1:4, function(i) distributionFunction(i, 1:4))
```

## B)

### i)
$$
\begin{aligned}
A_S^{(l, 1)}(4) &= \sum_{i = 1}^{2^1 - 1} \Bigg( F_{X_1, X_2}\bigg(\frac{i}{2^1}\times 4, \frac{2^1 - i}{2^1}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{2^1}\times 4, \frac{2^1 - i}{2^1}\times 4\bigg) \Bigg) \\
&= \Bigg( F_{X_1, X_2}\bigg(\frac{1}{2^1}\times 4, \frac{2^1 - 1}{2^1}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{1 - 1}{2^1}\times 4, \frac{2^1 - 1}{2^1}\times 4\bigg) \Bigg) \\
&= \Bigg( F_{X_1, X_2}\bigg(\frac{1}{2}\times 4, \frac{1}{2}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{0}{2}\times 4, \frac{1}{2}\times 4\bigg) \Bigg) \\
&= \Bigg( F_{X_1, X_2}\big(2, 2\big) - F_{X_1, X_2}\big(0, 2\big) \Bigg) \\
&= `r distributionFunction(2, 2) - distributionFunction(0,2)`
\end{aligned}
$$

### ii)
$$
\begin{aligned}
A_S^{(l, 2)}(4) &= \sum_{i = 1}^{2^2 - 1} \Bigg( F_{X_1, X_2}\bigg(\frac{i}{2^2}\times 4, \frac{2^2 - i}{2^2}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{2^2}\times 4, \frac{2^2 - i}{2^2}\times 4\bigg) \Bigg) \\
&= \sum_{i = 1}^{3}\Bigg( F_{X_1, X_2}\bigg(\frac{i}{4}\times 4, \frac{4 - i}{4}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{4}\times 4, \frac{4 - i}{4}\times 4\bigg) \Bigg) \\
&= \sum_{i = 1}^{3}\Bigg( F_{X_1, X_2}\bigg(i, (4 - i)\bigg) - F_{X_1, X_2}\bigg((i - 1), (4 - i)\bigg) \Bigg) \\
&= `r sum(sapply(1:3, function(i) distributionFunction(i, (4 -i)) - distributionFunction((i - 1), (4 -i))))`
\end{aligned}
$$

## C)

### i)
$$
\begin{aligned}
A_S^{(u, 1)}(4) &= \sum_{i = 1}^{2^1} \Bigg( F_{X_1, X_2}\bigg(\frac{i}{2^1}\times 4, \frac{2^1 + 1 - i}{2^1}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{2^1}\times 4, \frac{2^1 + 1 - i}{2^1}\times 4\bigg) \Bigg) \\
&= \sum_{i = 1}^{2} \Bigg( F_{X_1, X_2}\bigg(\frac{i}{2}\times 4, \frac{2 + 1 - i}{2}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{2}\times 4, \frac{2 + 1 - i}{2}\times 4\bigg) \Bigg) \\
&= `r sum(sapply(1:2, function(i) distributionFunction(i, (4 -i)) - distributionFunction((i - 1), (4 -i))))`
\end{aligned}
$$

### ii)
$$
\begin{aligned}
A_S^{(u, 2)}(4) &= \sum_{i = 1}^{2^2} \Bigg( F_{X_1, X_2}\bigg(\frac{i}{2^2}\times 4, \frac{2^2 + 1 - i}{2^2}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{2^2}\times 4, \frac{2^2 + 1 - i}{2^2}\times 4\bigg) \Bigg) \\
&= \sum_{i = 1}^{4}\Bigg( F_{X_1, X_2}\bigg(\frac{i}{4}\times 4, \frac{5 - i}{4}\times 4\bigg) - F_{X_1, X_2}\bigg(\frac{i - 1}{4}\times 4, \frac{5 - i}{4}\times 4\bigg) \Bigg) \\
&= \sum_{i = 1}^{4}\Bigg( F_{X_1, X_2}\bigg(i, (5 - i)\bigg) - F_{X_1, X_2}\bigg((i - 1), (5 - i)\bigg) \Bigg) \\
&= `r sum(sapply(1:4, function(i) distributionFunction(i, (5 -i)) - distributionFunction((i - 1), (5 -i))))`
\end{aligned}
$$

## D)
```{r}
## Méthode upper
upperDistribution <- function(s, m){
     division <- 2^m
     sum(sapply(1:(division - 1), function(i) 
          distributionFunction(i / division * s, (division - i) / (division) * s) - 
               distributionFunction( (i - 1)/ division * s, (division - i) / (division) * s)))
}

## Méthode lower
lowerDistribution <- function(s, m){
     division <- 2^m
     sum(sapply(1:division, function(i) 
          distributionFunction(i / division * s, (division + 1 - i) / (division) * s) - 
               distributionFunction( (i - 1)/ division * s, (division + 1 - i) / (division) * s)))
}
```

```{r}
### A lower m1
sapply(seq(0, 10, by = 0.1), function(i) upperDistribution(i, 5))
### A lower m2
sapply(seq(0, 10, by = 0.1), function(i) upperDistribution(i, 10))
### A upper m1
sapply(seq(0, 10, by = 0.1), function(i) lowerDistribution(i, 5))
### A upper m2
sapply(seq(0, 10, by = 0.1), function(i) lowerDistribution(i, 10))
```

