---
title: "10_3Q1"
author: "David Beauchemin"
date: "1 décembre 2017"
output: pdf_document
---


# 10_3Q1 (similaire à 10_2Q9)

```{r}
#Vecteur des Yi
Yi <- matrix(c(1.41, -0.32, 1.07, 0.98, -0.75, 1.87), nrow = 3 , ncol = 2, byrow = TRUE)

# Pareto
qpareto <- function(kappa, lambda, alpha){
     lambda * ((1 - kappa)^(-1 / alpha) - 1)
}
```

## A)
### i)
$$
\begin{aligned}
M_{Y_1, Y_2}(t_1, t_2) &= E\bigg[ e^{t_1 \times y_1} e^{t_2 \times y_2}\bigg] \\
&= E\big[ e^{t_1 \times y_1 + t_2 \times y_2}\big] \\
&= e^{E\big[ t_1 \times w_1 + t_2 \times (c\times w_1 + \sqrt{1 - c^2}\times w_2)\big]} \\
&= e^{E[t_1 \times w_1] + E[t_2 \times c\times w_1] + E[t_2\sqrt{1 - c^2}\times w_2]} \\
&= e^{\mu_1 \times t_1 + \mu_1 \times t_2 + t_2\sqrt{1 - c^2}\times\mu_2} \\
&= M_{Y_1}(t_1)M_{Y_1}(t_2)M_{Y_2}(t_2\sqrt{1 - c^2})
\end{aligned}
$$

### ii)
$$
\begin{aligned}
M_{Y_1} &= M_{Y_1, Y_2}(t_1, 0) \\
&= E\bigg[ e^{t_1 \times x_1 + 0 \times x_2}\bigg] \\
&= E\big[e^{ t_1 \times y_1 }\big] \\
&= M_{Y_1}(t_1)
\end{aligned}
$$

### iii)
$$
\begin{aligned}
M_{Y_2} &= M_{Y_1, Y_2}(0, t_2) \\
&= E\bigg[ e^{0 \times x_1 + t_2 \times x_2}\bigg] \\
&= E\big[e^{ t_2 \times y_1 }\big] \\
&= E\big[e^{ t_2 \times (c\times w_1 + \sqrt{1 - c^2}\times w_2) }\big] \\
&= M_{Y_1}(t_2)M_{Y_2}(t_2\sqrt{1 - c^2})
\end{aligned}
$$

#### iv)
Les variables ne sont pas indépendante et sont une loi normale standard bivariée.

## B)
Il faut d'abord créé des valeurs d'un couple de loi normale bivariées $(Z_1, Z_2)$, soit
$$
\begin{aligned}
Y_1 &= Z_1 & Y_2 &=  \alpha Z_1 + \sqrt{1 - \alpha^2} * Z_2
\end{aligned}
$$
On rappel que dans notre cas $\alpha$ correspond au coefficiet de corrélation de Person. (Voir page 327 du document de référence)

```{r}
alpha <- 0.7
Zi <- matrix(c(Yi[,1], alpha * Yi[,1] + sqrt(1 - alpha^2) *  Yi[,2]), nrow = 3)
Zi
```

```{r}
U <- matrix(pnorm(Zi), nrow = 3, ncol = 2)
U
```

## C)

```{r}
X <- matrix(c(qpareto(U[ ,1], 900, 1.9), qexp(U[ ,2], 1 / 1000)), nrow = 3, ncol = 2)
X
```

## D)

```{r}
S <- rowSums(X)
S
```

## E)
```{r}
mean(X[,1] * (S > 2000))
```
