---
title: "10_4Q1"
author: "David Beauchemin"
date: "6 décembre 2017"
output: pdf_document
---

# 10_4Q1

## A)
Il s'agit de la borne supérieur de Fréchet $C^+(u_1, u_2)$.
$$
\begin{aligned}
E[M_1M_2] &= \sum_{i = 1}^{10}\sum_{j = 1}^{10}\overline{F}_{M_1, M_2}(k_{1, i}k_{2, j}) \\
\end{aligned}
$$

```{r}
sum(sapply(0:10, 
           function(j) sapply(0:10, 
                              function(i)min(1 - pbinom(i, 10, 0.3), 1 - pbinom(j, 10, 0.2)))))
```

$$
\begin{aligned}
E[M_1] &= n \times q_1 \\
&= 10 \times 0.3 \\
&= 3 \\
E[M_2] &= n \times q_2 \\
&= 10 \times 0.2 \\
&= 2 \\
\text{Var}(M_1) &= n \times q_1 \times (1 - q_1) \\
&= 10 \times 0.3  \times (1 - 0.3)\\
&= 2.1 \\
\text{Var}(M_2) &= n \times q_2 \times (1 - q_1) \\
&= 10 \times 0.2 \times (1 - 0.2)\\
&= 1.6
\end{aligned}
$$

```{r}
EM1M2 <- sum(sapply(0:10, 
                    function(j) sapply(0:10, function(i)min(1 - pbinom(i, 10, 0.3), 
                                                            1 - pbinom(j, 10, 0.2)))))
EX1 <- 3
EX2 <- 2
VarX1 <- 2.1
VarX2 <- 1.6
## Covariance
covM1M2 <-  EM1M2 - EX1*EX2
```

```{r}
## Calcul de rho
(rho <- covM1M2 / (sqrt(VarX1) * sqrt(VarX2)))
```

## B)
Il s'agit de la borne inférieur de Fréchet $C^-(u_1, u_2)$.
$$
\begin{aligned}
E[M_1M_2] &= \sum_{i = 1}^{10}\sum_{j = 1}^{10}\overline{F}_{M_1, M_2}(k_{1, i}k_{2, j}) \\
\end{aligned}
$$

```{r}
sum(sapply(0:10, 
           function(j) sapply(0:10, function(i)max(1 - pbinom(i, 10, 0.3) + 
                                                        1 - pbinom(j, 10, 0.2) - 1, 0))))
```

$$
\begin{aligned}
E[M_1] &= n \times q_1 \\
&= 10 \times 0.3 \\
&= 3 \\
E[M_2] &= n \times q_2 \\
&= 10 \times 0.2 \\
&= 2 \\
\text{Var}(M_1) &= n \times q_1 \times (1 - q_1) \\
&= 10 \times 0.3  \times (1 - 0.3)\\
&= 2.1 \\
\text{Var}(M_2) &= n \times q_2 \times (1 - q_1) \\
&= 10 \times 0.2 \times (1 - 0.2)\\
&= 1.6
\end{aligned}
$$

```{r}
EM1M2 <- sum(sapply(0:10, 
                    function(j) sapply(0:10, function(i)max(1 - pbinom(i, 10, 0.3) + 
                                                                 1 - pbinom(j, 10, 0.2) - 1, 0))))
EX1 <- 3
EX2 <- 2
VarX1 <- 2.1
VarX2 <- 1.6
## Covariance
covM1M2 <-  EM1M2 - EX1*EX2
```

```{r}
## Calcul de rho
(rho <- covM1M2 / (sqrt(VarX1) * sqrt(VarX2)))
```


## C)

### i)
$$
\begin{aligned}
E[X_1] &= 3 \\
E[X_2] &= 2 \\
\end{aligned}
$$

Il faut alors que $E[X_1X_2] = 6$, soit
```{r}
EM1M2.Sup <- sum(sapply(0:10, 
                        function(j) sapply(0:10, function(i)max(1 - pbinom(i, 10, 0.3) + 1 - 
                                                                     pbinom(j, 10, 0.2) - 1, 0))))
EM1M2.Inf <- sum(sapply(0:10, 
                        function(j) sapply(0:10, function(i)min(1 - pbinom(i, 10, 0.3), 
                                                                1 - pbinom(j, 10, 0.2)))))

EX1X2.function <- function(theta) {
     theta * EM1M2.Sup + (1 - theta) * EM1M2.Inf
}

f.optim <- function(theta) abs(EX1X2.function(theta) - 6)
optimize(f.optim, interval = c(0, 1))$minimum
```

On résout pour trouver $\alpha = 0.5075135$ qui satisfait l'équation.

### ii)
```{r}
densityFunction <- function(m1, m2, FM1M2){
     ifelse(m1 - 1 < 0 || m2 - 1 < 0, FM1M2(m1, m2), 
            FM1M2(m1, m2) - FM1M2(m1 - 1, m2)  - FM1M2(m1, m2 - 1) +
          FM1M2(m1 - 1, m2 - 1))
}

FM1M2.sup <- function(M1, M2){
     min(pbinom(M1, 10, 0.3),  pbinom(M2, 10, 0.2))
}
FM1M2.inf <- function(M1, M2){
     max(pbinom(M1, 10, 0.3) + pbinom(M2, 10, 0.2) - 1, 0)
}
FM1M2.nonCor <- function(M1, M2, theta = 0.5075135){
     theta * min(pbinom(M1, 10, 0.3),  pbinom(M2, 10, 0.2)) + 
          (1 - theta) * max(pbinom(M1, 10, 0.3) + pbinom(M2, 10, 0.2) - 1, 0)
}
```


```{r}
k <- c(0, 8, 10)

## Monotone
sapply(k, function(k) sum(sapply(0:10, function(j) sapply(0:10, function(i) 
     max(i + j - k, 0) * densityFunction( i, j, FM1M2.sup) ))))

## Antimonotone
sapply(k, function(k) sum(sapply(0:10, function(i) sapply(0:10, function(j) 
     max(i + j - k, 0) * densityFunction( i, j, FM1M2.inf) ))))

## Indépendant
sapply(k, function(k) sum(sapply(0:10, function(j) sapply(0:10, function(i) 
     max(i + j - k, 0) * dbinom(i, 10, 0.3) * dbinom(j, 10, 0.2)))))

## Non-corrélé Theta = 0.5075135
sapply(k, function(k) sum(sapply(0:10, function(j) sapply(0:10, function(i) 
     max(i + j - k, 0) * densityFunction( m1 = i, m2 = j, FM1M2 = FM1M2.nonCor) ))))

```

### iii)
Deux $v.a.$ non-corrélées ne sont pas aussi indépendantes.
